# Generated by Django 4.2 on 2023-05-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashout',
            old_name='pay_type',
            new_name='mode',
        ),
    ]
