# Generated by Django 4.2 on 2023-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_pay_type_cashout_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='mode',
            field=models.CharField(choices=[('phone', 'Phone'), ('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('others', 'Others')], default='phone', max_length=6),
        ),
    ]
