# Generated by Django 4.2 on 2023-05-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='cashout',
            name='category',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
