# Generated by Django 4.2 on 2023-05-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_categories_cashout_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='category',
            field=models.CharField(choices=[('shopping', 'Shopping'), ('gifts', 'Gifts'), ('food', 'Food'), ('groceries', 'Groceries')], default='', max_length=20, null=True),
        ),
    ]
