# Generated by Django 4.2 on 2023-05-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cashout_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='mode',
            field=models.CharField(choices=[('phone_pay', 'Phone'), ('cash', 'Cash'), ('card_pay', 'Card'), ('cheque_pay', 'Cheque'), ('others', 'Others')], default='phone', max_length=10),
        ),
    ]
