# Generated by Django 4.2 on 2023-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cashout_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='mode',
            field=models.CharField(choices=[('phone_pay', 'Phone Pay'), ('cash', 'Cash'), ('card_pay', 'Card Pay'), ('cheque_pay', 'Cheque Pay'), ('others', 'Others')], default='phone_pay', max_length=10),
        ),
    ]
